# Generated by Django 5.2.10 on 2026-01-08 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Perfil de Funcionário",
                "verbose_name_plural": "Perfis de Funcionários",
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
